application: nomorebookmarks 
version: 1
runtime: python
api_version: 1

handlers:
- url: /img/logo.jpg
  static_files: img/logo.jpg
  upload: img/logo.jpg
- url: /img/google.gif
  static_files: img/google.gif
  upload: img/google.gif
- url: /img/star.gif
  static_files: img/star.gif
  upload: img/star.gif
- url: /css/nomorebookmarks.css
  static_files: css/nomorebookmarks.css
  upload: css/nomorebookmarks.css
- url: .*
  script: nomorebookmarks.py
